config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pictures/create'
  devise_for :users, path_prefix: 'my'
  resources :users
  resources :events do
    resources :attendances
    resources :pictures, only: [:create]
  end
  root to: 'events#index'
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :admin, class_name: 'User'
  has_one_attached :picture
  has_many :attendances
  has_many :attendees, through: :attendances, source: :attendee
  validates :start_date, presence: true
  validate :start_date_cannot_be_in_the_past
  validates :duration, presence: true,
                       numericality: { only_integer: true, greater_than: 0 }
  validate :duration_is_multiple_of_5
  validates :title, presence: true,
                    length: { in: 5..140 }
  validates :description, presence: true,
                          length: { in: 20..1000 }
  validates :price, presence: true,
                    numericality: { greater_than: 0, less_than: 1001 }
  validates :location, presence: true
  validates :picture, presence: true

  def end_date
    start_date + duration * 60
  end

  private

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def duration_is_multiple_of_5
    if duration.present? && duration.instance_of?(Integer) && ((duration % 5) != 0)
      errors.add(:duration, 'shall be a multiple of 5')
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy], alert: 'You must sign in first!'
  before_action :admin_only, only: %i[edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    event_creation = event_params.clone
    event_creation[:admin_id] = current_user.id

    @event = Event.new(event_creation)
    # pic_path = Dir.getwd + '/lib/assets/simple_neuron.png'
    # @event.picture.attach(io: File.open(pic_path), filename: ('picture ' + @event.title.to_s + '.png'))

    @event.picture.attach(event_params[:picture])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, alert: "Your event can not be created: #{@event.errors.messages}" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    event_title = @event.title

    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event '#{event_title}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def admin_only
    @event = Event.find(params[:id])
    unless @event.admin == current_user
      redirect_to root_url, alert: 'Modifying the event of another user is forbidden.'
    end
  end

  # # Use callbacks to share common setup or constraints between actions.
  # def set_event
  #   @event = Event.find(params[:id])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:admin_id, :start_date, :duration, :title, :description, :price, :location, :picture)
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_events_table.html.erb
<div class="table-responsive">
<table class="table table-dark">
  <thead>
    <tr>
      <th>Start date</th>
      <th>Duration</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= event.start_date %></td>
        <td><%= event.duration.to_s + ' min' %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.price.to_s + ' €' %></td>
        <td><%= event.location %></td>
        <td><%= button_to 'Show', event %></td>
        <% if event.admin == current_user %>
        <td><%= button_to 'Edit', edit_event_path(event), method: :get %></td>
        <td><%= button_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

<%= form_with(model: event, local: true,  multipart: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <p>You are the manager of this event.</p>
  <br>
  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="form-group">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="form-group">
    <%= form.label :picture %>
    <%= form.file_field  :picture  %>
  </div>

  <div class="actions mt-5">
    <%= form.submit %>
  </div>
  <% end %>

    <div class="form-group">
  <strong>Picture</strong>
  <%if @event.picture.attached?%>
  <%= image_tag @event.picture, alt: 'Picture', style: "max-width: 450px"  %>
  <% end %>
  </div>


      </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <!-- Content here -->

<br>

<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<div class="container">

<h1>Events</h1>
<br />

<div class="table-responsive">
<table class="table table-dark">
  <thead>
    <tr>
      <th>Admin</th>
      <th>Start date</th>
      <th>Duration</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Location</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.admin.email %></td>
        <td><%= event.start_date %></td>
        <td><%= event.duration.to_s + ' min' %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.price.to_s + ' €' %></td>
        <td><%= event.location %></td>
        <td><%= button_to 'Show', event, method: :get %></td>
        <!-- <td><%= button_to 'Edit', edit_event_path(event.id), method: :get %></td>
   -->
        <% if (user_signed_in? && (event.admin == current_user)) -%>
        <td><%= button_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br />

</div>

app/views/events/new.html.erb
<div class="container">
  <!-- Content here -->
<br>
<h1>New Event</h1>
<br>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<div class="container">
  <!-- Content here -->


<p>
  <strong>Admin:</strong>
  <%= @event.admin.email %>
</p>

<p>
  <%if @event.picture.attached?%>
  <%= image_tag @event.picture, alt: 'Event picture', style: "max-width: 450px"%>
  <% end %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration.to_s + ' min' %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price.to_s + ' €' %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%if user_signed_in? -%>
  <%if current_user == @event.admin -%> 
  <%= button_to 'Edit', edit_event_path(@event), method: :get %> 
  <% end -%>


<%unless @event.attendees.include?(current_user) -%>
    <%= button_to 'Attend', new_event_attendance_path(@event.id), method: :get %> 
<% end -%>
<% end -%>
  <%= button_to 'Back', events_path, method: :get %>

<p>
  <br>
  <% if @event.attendees.size > 0 -%>
  <strong>Attendees:</strong>
  <% @event.attendances -%>
  <%= render partial: "attendances/index", locals: {attendances: @event.attendances} %>
  <%else -%>
  <strong>No attendee for this event yet.</strong>
  <% end -%>
  <br>
</p>



</div>