config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pictures/create'
  devise_for :users, path_prefix: 'my'
  resources :users
  resources :events do
    resources :attendances
    resources :pictures, only: [:create]
  end
  root to: 'events#index'
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  after_create :new_attendee_notif_to_admin_email
  belongs_to :event
  belongs_to :attendee, class_name: 'User'
  validates :stripe_customer_id, presence: true, uniqueness: true

  def new_attendee_notif_to_admin_email
    AttendanceMailer.new_attendee_notif_to_admin_email(event.admin, attendee, event).deliver_now
  end
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController
  before_action :set_event
  before_action :set_attendance, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :attendee_or_admin, only: [:index]
  before_action :current_attendee_or_admin, only: %i[update destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show; end

  # GET /attendances/new
  def new
    # @event = Event.find(params[:event_id])
    @attendance = Attendance.new(attendee: current_user, event: @event, stripe_customer_id: '1111111111')
    puts '$' * 50
    puts
    tp @attendance
    puts @attendance.errors.messages
    puts
  end

  def create
    # @event = Event.find(params[:event_id])

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur'
    )

    @attendance = Attendance.new(stripe_customer_id: charge.customer,
                                 attendee: current_user,
                                 event_id: params[:event_id])

    if @attendance.save!
      redirect_to @event, notice: 'You have successfully registered to this event.'
    else
      redirect_to new_event_attendance_path(@event),
                  alert: "Your attendance to this event has been rejected: #{@attendance.errors.messages}"
    end
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_event_attendance_path(@event), alert: flash[:error]
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_attendance
    @attendance = Attendance.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attendance_params
    params.require(:attendance).permit(:event_id, :attendee_id, :stripe_customer_id)
  end

  def attendee_or_admin
    unless (@event.admin == current_user) || @event.attendees.include?(current_user)
      flash[:danger] = 'Back off ! Not your event !'
      redirect_to root_path, notice: 'You need to attend or manage this event to see the list of attendees.'
    end
  end

  def current_attendee_or_admin
    unless (@event.admin == current_user) || (@eattendance.attendee == current_user)
      flash[:danger] = 'Back off ! Not your event !'
      redirect_to root_path, notice: 'You can only modify your own attendances, or attendances of your own event.'
    end
  end

  def set_event
    @event = Event.find(params[:event_id])
    @amount = @event.price * 100
  end
end

app/helpers/attendances_helper.rb
# frozen_string_literal: true

module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :stripe_customer_id %>
    <%= form.text_field :stripe_customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/_index.html.erb
<div class="table-responsive">
<table class="table table-dark">
  <thead>
    <tr>
      <% if defined? context %>
       <% unless context == 'show_event' -%>
      <th>Event</th>
        <% end -%>
      <% end -%>
      <th>Attendee</th>
      <th>Stripe customer id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% attendances.each do |attendance| %>
      <tr>
          <% if defined? context %>
         <% unless context == 'show_event' -%>
        <td><%= attendance.event.title %></td>
        <% end -%>
          <% end -%>
        <td><%= attendance.attendee.email %></td>
        <td><%= attendance.stripe_customer_id %></td>
        <td><%= button_to 'Show', event_attendance_path(attendance.event.id), method: :get %></td>
      <% if current_user == attendance.attendee-%>
        <td><%= button_to 'Destroy', event_attendance_path(attendance.event.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br />

app/views/attendances/create.html.erb
<div class="container">

<br>
<h1>Attendance created ! </h1>

</div>

app/views/attendances/edit.html.erb
<div class="container">
  <!-- Content here -->

<br>


<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', event_attendance_path(@attendance.event.id) %> |
<%= link_to 'Back', event_attendances_path(@attendance.event.id) %>
</div>

app/views/attendances/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Attendances</h1>
<div class="table-responsive">
<table class="table table-dark">
  <thead>
    <tr>
      <th>Event</th>
      <th>User</th>
      <th>Stripe customer</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.event %></td>
        <td><%= attendance.attendee %></td>
        <td><%= attendance.stripe_customer_id %></td>
        <td><%= button_to 'Show', attendance, method: :get %></td>
<!--         <td><%= button_to 'Edit', edit_attendance_path(attendance), method: :get %></td>
        <td><%= button_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br />

</div>

app/views/attendances/new.html.erb
<div class="container">
<br>
<h2>Join this event</h1>
  <p> <strong> Title: </strong>  <%= @event.title %>  </p>
<p> <strong> Description: </strong>  <%= @event.description %>   </p>
  <p> <strong>Date: </strong><%= @event.start_date.strftime("%F") %></p>
  <p> <strong>At: </strong><%= @event.start_date.strftime("%T") %></p>
<br />
<%= form_tag event_attendances_path(@event), method: :post do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $<%= (@amount/100) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description= "Event paiement"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
<% end %>
</div>

app/views/attendances/show.html.erb
<div class="container">
  <!-- Content here -->

<br>

<p id="notice"><%= notice %></p>

<p>
  <strong>Event title:</strong>
  <%= @attendance.event.title %>
</p>

<p>
  <strong>Attendee:</strong>

<%= @attendance.attendee.email %>
</p>

<p>
  <strong>Stripe customer:</strong>
  <%= @attendance.stripe_customer_id %>
</p>

<%= link_to 'Back to Event', event_path(@attendance.event.id) %>
</div>